"""JSON schema definitions for payload validation."""

LEAD_SCHEMA = {
    "type": "object",
    "required": ["company", "first_name", "last_name", "email", "phone"],
    "additionalProperties": False,
    "properties": {
        "company": {"type": "string", "minLength": 1},
        "first_name": {"type": "string", "minLength": 1},
        "last_name": {"type": "string", "minLength": 1},
        "job_title": {"type": "string"},
        "email": {
            "type": "string",
            "format": "email",
            "pattern": r"^[^@\s]+@[^@\s]+\.[^@\s]+$",
        },
        "phone": {
            "type": "string",
            "pattern": r"^\+?[\d\s\-().]{7,20}$",
        },
        "fax": {"type": "string"},
        "mobile": {"type": "string"},
        "website": {"type": "string"},
        "industry": {"type": "string"},
        "lead_source": {"type": "string"},
        "lead_status": {"type": "string"},
        "no_of_employees": {"type": ["integer", "string"]},
        "annual_revenue": {"type": ["number", "string"]},
        "street": {"type": "string"},
        "city": {"type": "string"},
        "state": {"type": "string"},
        "zip_code": {"type": "string"},
        "country": {"type": "string"},
        "email_opt_out": {"type": ["boolean", "string"]},
        "created_by": {"type": "string"},
        "modified_by": {"type": "string"},
        "last_activity_time": {"type": "string"},
        "description": {"type": "string"},
        "sales_person": {"type": "string"},
        "created_time": {"type": "string"},
        "lead_owner": {"type": "string"},
        "product_interest": {"type": "string"},
        "message": {"type": "string"},
        "source_type": {"type": "string"},
        "task_owner": {"type": "string"},
        "related_to": {"type": "string"},
        "task_status": {"type": "string"},
        "task_priority": {"type": "string"},
        "task_tag": {"type": "string"},
        "notes": {"type": "string"},
        "attachments": {"type": ["array", "string"]},
        "reminder": {"type": ["boolean", "string"]},
        "repeat": {"type": ["boolean", "string"]},
        "closed_time": {"type": "string"},
        "contact_name": {"type": "string"}
    },
}
